### ISSUE TITLE
[Frontend] My Page

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#11]
## Overview
Implement my page
<img width="296" alt="image" src="https://github.com/user-attachments/assets/b36fc029-b0e9-4807-b1d7-34b1a338cd7a" />

## Acceptance Criteria
- The display should match the design.
- The thumbnail should be changeable.
- The ID should be copyable.
- The username should be editable.
- The language setting should be changeable.
- The account should be deletable.
- The user should be able to log out.

## Task
- [x] Display the icon, email address, ID, username, and language setting retrieved from the API response.
- [x] Make the ID copyable.
- [x] Make the username editable.
- [x] Allow the language setting to be changed.
- [x] Allow the account to be deleted.
- [x] After logging out, redirect to the Home screen.
