### ISSUE TITLE
[Frontend] Friend Management Page

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#12]
## Overview
Implement friend management page

<img width="431" alt="Image" src="https://github.com/user-attachments/assets/bad3dd7a-6d85-44ff-a03d-be33c4e0aaab" />

## Acceptance Criteria
- The input for adding friends is displayed
- The relevant data is retrieved during the search
- Existing friends are displayed
- Friends with pending requests are displayed
- Friends waiting for approval are displayed
- The approval status can be sent to the backend

## Task
- [x] Create components to display existing friends, friends with pending requests, and friends waiting for approval
- [x] Add "Approve" and "Reject" buttons
- [x] Add the button to delete existing friends
