### ISSUE TITLE
Meeting Notes (2024/12/18)

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#14]
# 2024/12/18 11:30~

**Attendees**: Ben, Haruka, Risa

### 🔸 Ben
   - As a progress, verifying a pull request(Google authentication)

### 🔸 Haruka
   - All tasks on hand have been completed

### 🔸 Risa
   - No progress
   
## Discussion
- [UI] Ensure that the 'Complete Edit' button is always displayed in its default state on the record creation screen

---

## Tasks
- **Ben**
  - [x] Verify and research Google authentication.
  - [x] Decide whether to include `gameID` in the turns table and how to handle unknown data.

- **Haruka**
  - [ ] Create API documentation

- **Risa**
  - [x] Implement the navigation part (#13 )
