### ISSUE TITLE
Meeting Notes (2024/12/19)

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#20]
# 2024/12/19 14:30~

**Attendees**: Ben, Haruka, Risa

### 🔸 Ben
   - Auth PR(Google authentication) has been checked and merged.
   - The database design is complete (the chart has also been updated).
   - The database connection and Supabase setup have been done, and users can now register in the database after logging in.

### 🔸 Haruka
   - In the middle of creating the API documentation based on the following article: 
  [ https://zenn.dev/mo_ri_regen/articles/swagger- api-document](https://zenn.dev/mo_ri_regen/articles/swagger-api-document)
   - Once the API documentation is complete, I will have Ben review it (and store it in the docs/api folder).

### 🔸 Risa
   - Navigation implementation and conflict resolution are complete.
   - Implementation of the "My Page" is in progress.

### Regarding testing:
- Initially, we will write out the test cases and execute them manually.
- Currently, the frontend development is ahead, so Risa will write the test cases for each screen in the spreadsheet and execute the tests where possible. Ben will review the test cases when creating the PR.

---

## Tasks
- **Ben**
  - [x] Merge navigation pull request
  - [x] Merge supabase setup pull request
  - [x] Create a whole DB scheme
  - [x] Review API documentation
  - [x] Review test cases

- **Haruka**
  - [x] Create API documentation

- **Risa**
  - [x] Implement mypage #11 
  - [x] Write the test cases

---

## Memo
- Share the env data in a different channel on Discord.(Ben)
- Please install Copilot.(Ben)
- ❤️❤️❤️ Happy Birthday Ben ❤️❤️❤️
