### ISSUE TITLE
Meeting Notes (2024/12/20)

### ISSUE THREAD

**Issue by kakimaru** [NelsoNave/mahjong-app#23]
# 2024/12/20 16:30~

**Attendees**: Ben, Haruka, Risa

### 🔸 Ben
- To prevent becoming a bottleneck, I want to prepare tasks in advance.
- I have set up navigation and Supabase.
- I reviewed the API document PR.
- I will review the test case created by Risa.
- Regarding the connection issue with Prisma.
  - It might be caused by Wi-Fi
  - I have prepared steps to resolve the local environment setup issue.
  - My upcoming tasks include:
    - Reviewing
    - Studying Prisma

### 🔸 Haruka
- I am still creating the API document.

### 🔸 Risa
- I've finished creating the My page feature, but I want to use server actions from Next.js.
  - I will update my pull request.
  - I also want to create test cases.

---

## Tasks
- **Ben**
  - [x] Prepare Risa's task
  - [x] Solve Prisma connection
  - [x] Review the test case created by Risa 

- **Haruka**
  - [x] Create a matrix to align everyone's understanding
  - [x] finish friends api

- **Risa**
  - [x] Update my page
  - [x] Create test case
