### ISSUE TITLE
Meeting Notes (2024/12/24)

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#31]
# 2024/12/24 11:00~

**Attendees**: Ben, Haruka, Risa

### 🔸 Ben
   - Implementing the backend for the MyPage. Will be testing pending test cases
   -  All database table schemas have been created
   - Test records have been created
   - Created a Google authentication login page for testing purposes
   - The API documentation is almost complete

### 🔸 Haruka
  -  Currently implementing the record creation page and will be preparing a PR soon
  - Since there are layout (including font) changes, it might be better to create a PR for that first
     (Suggestion: It might be a good idea to create a separate branch for the layout changes. - Ben)

### 🔸 Risa
   - Completed the test cases for friend management
   - Currently conducting tests
   - Implement a chart and timeline on the record page

### Frontend
- The number of users on the record creation page will be fixed (it will not be possible to change the number later)
- Free Mahjong will not be implemented for now
- The URL will use kebab-case
- File names (paths) will be changed (e.g., "result" → "stats", and "record" might also be changed. - Ben)
- Navigation will be consolidated into the layout (Risa's task)
- All messages displayed on the screen will be received from the backend (both for success and failure)

### Meeting Notes
- If a task for any issue is completed, it should be closed immediately

### Task Allocation
- Mypage : frontend: Risa / backend: Ben
- Friend management : frontend: Risa / backend: Haruka
- New record : frontend: Risa or Haruka / backend: Ben
- Stats : frontend: Risa or Haruka / backend : Ben

---

## Tasks
- **Ben**
  - [x] Implement the backend for Mypage
  - [x] Testing of Mypage
  - [x] Finalizing API documentation
  - [x] Reviewing the PR for the Friend mangenant page
  - [x] Take over the implement the backend for the record creation page

- **Haruka**
  - [x]  Create a PR for the record creation page
  - [x] Start implementing the backend for friend management

- **Risa**
  - [x] Complete testing for the friend management page
  - [x] Create a PR for the friend management page
  - [x] Implement a chart and timeline on the new record page
  - [x] Implement the header component and refactor the navigation component
