### ISSUE TITLE
Meeting Notes (2024/12/25)

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#34]
# 2024/12/25 13:10~

**Attendees**: Ben, Haruka, Risa

### 🔸 Ben
   - Working on the backend implementation for the Mypage
   (It took time to catch up with Server Actions, but I believe it was a necessary investment for the future.)
   (Haruka should refer to this source code when implementing the friend management screen.)

### 🔸 Haruka
  - Changed the URL name to "new-game"
  - Removed the "Free Mahjong" option
  - Once Ben's Mypage PR is merged, Haruka will start implementing the backend for the friend management page

### 🔸 Risa
   - PR for the friend management page has been created.
   -  Currently working on the scroll functionality for the results page

---

## Tasks
- **Ben**
  ※  Reference the previous minutes' todos

- **Haruka**
  - [x] Implementing the backend for the friend management page

- **Risa**
  - [x] Implement the scroll functionality for the result page
  - [x] Implement the chart functionality for the result page
