### ISSUE TITLE
Meeting Notes (2024/12/30) 

### ISSUE THREAD

**Issue by Risa2422** [NelsoNave/mahjong-app#45]
# 2024/12/30 20:00~

**Attendees**: Ben, Haruka, Risa

### 🔸 Ben
 - Reviewed the "Create New Record" page
 - Currently working on the backend implementation for the game-related pages
 - Made changes to the yaml files

### 🔸 Haruka
 - Currently implementing the backend for friend management
 - Implementation for search and adding (sending requests) has been completed
 - Stuck on the "Get All Friends" part
 
### 🔸 Risa
 - Completed the implementation and testing of Navigation and Header
 - Currently working on the status management for the stats page
---

## Tasks
- **Ben**
  - [x] Complete implementation the game-related pages
  - [x] Start implementing backend of the result page

- **Haruka**
  - [x] Continue implementing the backend for friend management page

- **Risa**
  - [x]  Create PR for the header and navigation
  - [x]  Complete implementation for the stats page
